using CatBet.Models.AutoGenerated;
using CatBet.Models.Enums;
using CatBet.Services;

DataService dataService = new DataService();
var data = dataService.GetLocalData<RootFixtures>(JsonSelector.FixturesHeadToHead);

Console.WriteLine(data);