using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CatBet.Models.AutoGenerated
{
    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);

    public class Fixture
    {
        public int? Id { get; set; }
        public string Referee { get; set; }
        public string Timezone { get; set; }
        public DateTime Date { get; set; }
        public int? Timestamp { get; set; }
        public Periods Periods { get; set; }
        public Venue Venue { get; set; }
        public Status Status { get; set; }
        public int? Second { get; set; }
    }
}
