namespace CatBet.Models.AutoGenerated
{
    public class Home
    {
        public int? Id { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public bool? Winner { get; set; }
    }


}
