using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CatBet.Models.AutoGenerated
{
    public class RootFixtures
    {
        public string Get { get; set; }
        public Parameters Parameters { get; set; }
        public List<object> Errors { get; set; }
        public int? Results { get; set; }
        public Paging Paging { get; set; }
        public List<Response> Response { get; set; }
    }
}
