namespace CatBet.Models.AutoGenerated
{
    public class Status
    {
        public string Long { get; set; }
        public string Short { get; set; }
        public int? Elapsed { get; set; }
    }


}
